name: fbfmaproom2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cftime
  - dash
  - flask
  - numpy
  - opencv
  - pandas=1.3
  - psycopg2
  - rasterio
  - shapely=1.7
  - xarray
  - yaml
  - zarr
  - pip
  - pip:
    - dash-leaflet
    - pyaconf
    - queuepool
    - dash-bootstrap-components
