name: fbfmaproom2
channels:
  - conda-forge
  - defaults
dependencies:

    # rasterio build fails with python 3.10
    # https://github.com/rasterio/rasterio/issues/2333
  - python=3.9
  - cftime
  - dash
  - dash-leaflet
  - dash-bootstrap-components
  - numpy
  - opencv

    # Newer versions of Pandas do not appear to work correctly with queuepool.
    # In particular, how that package forms SQL query objects needs to be updated. 
    # Hopefully the solution here is to either send Igor a issue or to migrate to
    # a different connection pooling library
  - pandas=1.3
  - psycopg2
  - rasterio

    # Shapely changed how looping over geometries works in the newer version and
    # Pingrid relies on the old functionality. It is unclear to me whether using
    # the .geoms property has the same behavior as the "built in" iterator the
    # old version had. As we may migrate way from Pingrid and we're not going to
    # upgrade it right now and possibly waste the work or effort.
  - shapely=1.7

  - werkzeug<2.1 # werkzeug 2.1 spews warnings at dev server startup

  - xarray
  - yaml
  - zarr
  - pip
  - pip:
    - pyaconf
    - queuepool
