# App set up
core_path: /flex-fcst

# Forecast options
forecast_path: /data/xchourio/data/BMD-S2S-Data-Example/output
y_transform: true
start_regex: \w{3}-\w{1,2}-\w{4}
start_format_in: '%b-%d-%Y'
start_format_out: '%b-%-d-%Y'
forecast_mu_file_pattern: CFSv2_SubXPRCP_CCAFCST_mu_Apr_SLtarget.txt
forecast_var_file_pattern: CFSv2_SubXPRCP_CCAFCST_var_Apr_SLtarget.txt
obs_file_pattern: CFSv2_SubXPRCP_CCAFCST_obs_Apr_SLtarget.txt
hcst_file_pattern: CFSv2_SubXPRCP_CCAFCST_xvPr_Apr_SLtarget.txt
variable: Precipitation Anomaly

#S,L, target dates options
target_period_length: 7
time_units: days
leads: #provider_ID:leadTime_value
    wk1: 1
    wk2: 8
    wk3: 15
    wk4: 22
targets: null