# App set up
mode: debug  # debug, devel or prod
server: 127.0.0.1
port: 8050
core_path: /subseas-flex-fcst-maproom
admin_path: /subseas-flex-fcst-maproom-admin
tile_path: /subseas-flex-fcst-maproom-tiles
results_path: /data/xchourio/data/BMD-S2S-Data-Example/output
support_email: help@iri.columbia.edu
loglevel: info

# Forecast options
y_transform: true
forecast_mu_filePattern: CFSv2_SubXPRCP_CCAFCST_mu_Apr_*.txt
forecast_var_filePattern: CFSv2_SubXPRCP_CCAFCST_var_Apr_*.txt
obs_filePattern: CFSv2_SubXPRCP_CCAFCST_obs_Apr_*.txt
hcst_filePattern: CFSv2_SubXPRCP_CCAFCST_xvPr_Apr_*.txt
variable: Precipitation Anomaly

#S,L, target dates options
numberLeads: 4
dataLead1: wk1
lead1: 1
dataLead2: wk2
lead2: 8
dataLead3: wk3
lead3: 15
dataLead4: wk4
lead4: 22
target_period_length: 7

# Viz' set up
zoom: 7
