# App set up
mode: debug  # debug, devel or prod
server: 127.0.0.1
port: 8050
core_path: /subseas-flex-fcst-maproom
admin_path: /subseas-flex-fcst-maproom-admin
tile_path: /subseas-flex-fcst-maproom-tiles
results_path: /data/xchourio/data/BMD-S2S-Data-Example/output
support_email: help@iri.columbia.edu
loglevel: info

# Forecast options
y_transform: true
forecast_mu_filePattern: CFSv2_SubXPRCP_CCAFCST_mu_*.txt
forecast_mu_file: CFSv2_SubXPRCP_CCAFCST_mu_Apr_Apr-1-2022_wk1.txt #needed for Initialization
forecast_var_filePattern: CFSv2_SubXPRCP_CCAFCST_var_*.txt
obs_filePattern: CFSv2_SubXPRCP_CCAFCST_obs_*.txt
hcst_filePattern: CFSv2_SubXPRCP_CCAFCST_xvPr_*.txt
variable: Precipitation Anomaly
target_period_length: 6

# Viz' set up
zoom: 7
