mode: debug  # debug, devel or prod
server: 0.0.0.0
port: 8050
#prefix: https://iridl.ldeo.columbia.edu
core_path: /seas-flex-fcst-maproom
admin_path: /seas-flex-fcst-maproom-admin
tile_path: /seas-flex-fcst-maproom-tiles
results_path: /data/remic/pyCPTdev/working/testcca/
support_email: help@iri.columbia.edu
loglevel: info
y_transform: true
cpt_mos: CCA
forecast_mu_file: FORECAST_MU
forecast_var_file: FORECAST_VARIANCE
obs_file: PREDICTAND
hcst_file: CROSSVALIDATED_HINDCAST_VALUES
ccacorr_file: CCACORR
xccamap_file: XCCAMAP
fcst_pred_file: ORIGINAL_FCST_PREDICTOR
lead: 2.5
init_lat: 45.0
init_lng: -87.5
variable: Precipitation
colormap: "[0x000000 0xa52a2a 0xffa500 0xffff00 0xffe465 0xffe465 0x32cd32 0x40e0d0 0x0000ff 0xa020f0]"
colormapflipped: "[0xa020f0 0x0000ff 0x40e0d0 0x32cd32 0xffe465 0xffe465 0xffff00 0xffa500 0xa52a2a 0x000000]"
colormapcorrel: "[0x000080 0x0000ff 0x00bfff 0x7fffd4 0x98fb98 0xffe465 0xffe465 0xffff00 0xff8c00 0xff0000 0x800000]"
