# App set up
server: 0.0.0.0
port: 8063

# Forecast options
results_path: /data/remic/mydatafiles/ZMD/nextgenzmd
y_transform: false
start_regex: '[A-Z][a-z]{2}\d{4}'
start_format_in: '%b%Y'
start_format_out: '%b%Y'
forecast_mu_file_pattern: NextGen_PRCPPRCP_*FCST_mu_SLtarget.tsv
forecast_var_file_pattern: NextGen_PRCPPRCP_*FCST_var_SLtarget.tsv
obs_file_pattern: obs_PRCP_SLtarget.tsv 
hcst_file_pattern: None
variable: Precipitation

#S,L, target dates options
target_period_length: 3
time_units: months
leads: none
targets: ["Oct-Dec", "Nov-Jan", "Dec-Feb"]

# Viz' set up
zoom: 5
