# App set up
mode: debug  # debug, devel or prod
server: 127.0.0.1
port: 8050
core_path: /subseas-flex-fcst-maproom
admin_path: /subseas-flex-fcst-maproom-admin
tile_path: /subseas-flex-fcst-maproom-tiles
results_path: /data/xchourio/data/BMD-S2S-Data-Example/output
support_email: help@iri.columbia.edu
loglevel: info

# Forecast options
y_transform: true
forecast_mu_file: CFSv2_SubXPRCP_CCAFCST_mu_Apr_Apr-1-2022_wk1.txt
forecast_var_file: CFSv2_SubXPRCP_CCAFCST_var_Apr_Apr-1-2022_wk1.txt
obs_file: CFSv2_SubXPRCP_CCAFCST_obs_Apr_Apr-1-2022_wk1.txt
hcst_file: CFSv2_SubXPRCP_CCAFCST_xvPr_Apr_Apr-1-2022_wk1.txt
variable: Precipitation Anomaly

# Viz' set up
zoom: 7
