# App
core_path: /wat_bal_monit

# Zarr conversion
rr_mrg_nc_path: /Data/data23/ANACIM/anacim_v3/ALL_block2/rr_mrg_daily/
rr_mrg_resolution: .0375
rr_mrg_chunks:
    T: 592
    Y: 31
    X: 29
rr_mrg_zarr_path: /data/aaron/ANACIM/anacim_v3/ALL_block2/rr_mrg_daily

# Wat. Bal. Monit.
app_title: Soil Plant Water Balance Monitoring
planting_month: Jun
map_text:
    sm:
        menu_label: Soil Moisture
        description: The map shows the soil moisture...
        units: mm
    drainage:
        menu_label: Drainage
        description: The map shows the drainage...
        units: mm
