# App set up
mode: debug  # debug, devel or prod
server: 127.0.0.1
port: 8050
loglevel: info

db:
    dbname: iridb
    host: dlcomputemon1.iri.columbia.edu
    port: 5432
    user: ingrid  # user name
    password: SNIP

# Bangladesh
zoom: 7
shapes_adm:
     - name: Divisions
       color: black
       sql: select gid as key, name_1 as label, ST_AsBinary(the_geom) as the_geom
           from bangladesh_bmd_divisions
       is_checked: True
     - name: Districts
       color: black                      
       sql: select gid as key, (name_2 || ', ' || name_1) as label, ST_AsBinary(the_geom) as the_geom
           from bangladesh_bmd_districts
       is_checked: True
     - name: Upazillas
       color: grey
       sql: select gid as key, (name_3 || ', ' || name_2 || ', ' || name_1) as label, ST_AsBinary(the_geom) as the_geom
           from bangladesh_bmd_upazilas
       is_checked: False