logo: anacimLogo.jpg
institution: ANACIM
zoom: 7

datasets:
    shapes_adm:
        - name: Pays
          color: black
          sql: select id_0 as key, name_0 as label, ST_AsBinary(the_geom) as the_geom
                  from sen_adm0
          is_checked: False
        - name: Regions
          color: black
          sql: select id_1 as key, name_1 as label, ST_AsBinary(the_geom) as the_geom
              from sen_adm1
          is_checked: True

    # Daily ENACTS Zarr conversion
    daily:
        nc_path: /Data/data23/
        zarr_resolution: null #set to null for no regridding
        chunks: #consider changing chunk sizes if regridding
            T: 592
            Y: 31
            X: 29
        zarr_path: /data/remic/mydatafiles/
        vars:
           #var name in file name:
           #    - input file path relative to nc_path
           #    - output file path relative to zarr_path (set to null if same as input file path)
           #    - var name def in file
            precip: 
                - ANACIM/anacim_v3/ALL_block2/rr_mrg_daily/
                - null
                - precip
            tmax: 
                - ANACIM/anacim_v3/ALL_block2/tx_mrg_daily/
                - null
                - temp
            tmin: 
                - ANACIM/anacim_v3/ALL_block2/tn_mrg_daily/
                - null
                - temp
            et0:
                - ANACIM/anacim_v4/ET0/
                - ANACIM/anacim_v4/ET0/zarr/
                - et0

    # Dekadal ENACTS Zarr conversion
    dekadal:
        nc_path: /Data/data23/
        zarr_resolution: null #set to null for no regridding
        chunks: #consider changing chunk sizes if regridding
            T: 360
            Y: 31
            X: 29
        zarr_path: /data/remic/mydatafiles/
        vars:
           #var name in file name:
           #    - input file path relative to nc_path
           #    - output file path relative to zarr_path (set to null if same as input file path)
           #    - var name def in file
            precip: 
                - ANACIM/anacim_v3/ALL_block2/rr_mrg_dekad/
                - null
                - precip
            tmax: 
                - ANACIM/anacim_v3/ALL_block2/tx_mrg_dekad/
                - null
                - temp
            tmin: 
                - ANACIM/anacim_v3/ALL_block2/tn_mrg_dekad/
                - null
                - temp

    # Soil data
    taw_file: /data/remic/mydatafiles/soilgrids/Senegal/GYGA_ERZD_wat_cap_abs_anacim_enacts3.nc

    # Forecast data
    fcst_data:
        forecast_path: /data/remic/mydatafiles/ANACIM/cpt_demo/UCSBV3
        # All the below will be deprecated once no more partner outputs tsv files
        #forecast_mu_file_pattern: NextGen_PRCPPRCP_CCAFCST_mu_SLtarget.tsv
        #forecast_var_file_pattern: NextGen_PRCPPRCP_CCAFCST_var_SLtarget.tsv
        #obs_file_pattern: obs_PRCP_SLtarget.tsv
        #hcst_file_pattern: None
        #start_regex: '[A-Z][a-z]{2}\d{4}'
        #start_format_in: '%b%Y'
        #start_format_out: '%b%Y'
        # S,L, target dates options
        #leads: null
        #targets: ["Feb-May", "Jun-Sep"]
        #target_period_length: 4
        #time_units: months


maprooms:
    # Onset
    onset:
      - default_search_month: May
        default_search_month_cess: Sep
        default_running_days: 3
        default_min_rainy_days: 1
        ison_cess_date_hist: True
        map_text:
            length_mean:
                map_max: 180
            length_stddev:
                map_max: 40

    wat_bal:
      - planting_month: Jun
        crop_name: Rice
        kc_v: [0, 0, 1.1, 1.1, 0]
        kc_l: [3, 27, 45, 60]
        taw_max: 136
        
    monthly:
      - vars:
          Rainfall:
            max: 350
          Minimum Temperature:
            min: -5
            max: 40
          Maximum Temperature:
            min: -5
            max: 40
    
    crop_suitability:
      - map_text:
          precip:
            map_max: 400
            map_min: 0
          tmax:
            map_max: 42
            map_min: 10
          tmin:
            map_max: 32
            map_min: 0
        param_defaults:
          target_season: 1 #from DJF, MAM, JJA or SON
          lower_wet_thresh: 500 #mm; cumulative for the season
          upper_wet_thresh: 700 #mm; cumulative for the season
          min_temp: 10 #C
          max_temp: 25 #C
          temp_range: 15 #C; amplitude: `max_temp - min_temp`
          season_length: 75 #days 
          min_wet_days: 60 #days
          wet_day_def: 1 #mm

    flex_fcst:
      - y_transform: false
        variable: Precipitation
