# App set up
mode: debug  # debug, devel or prod
server: 127.0.0.1
port: 8050
loglevel: info

db:
    dbname: iridb
    host: dlcomputemon1.iri.columbia.edu
    port: 5432
    user: ingrid  # user name
    password: SNIP
    
# Ghana
logo: GMet_Logo.jpg
institution: GhanaMet
zoom: 6
shapes_adm:
        - name: Regions
          color: black
          sql: select gid as key, adm1_name as label, ST_AsBinary(the_geom) as the_geom
                  from g2015_2014_1 where gid between 688 and 697
          is_checked: True 
        - name: Districts
          color: grey
          sql: select gid as key, adm2_name as label, ST_AsBinary(the_geom) as the_geom
                  from g2015_2014_2 where gid between 6231 and 6446
          is_checked: True