# App set up
mode: debug  # debug, devel or prod
server: 127.0.0.1
port: 8050
loglevel: info

db:
    dbname: iridb
    host: dlcomputemon1.iri.columbia.edu
    port: 5432
    user: ingrid  # user name
    password: SNIP
    
# Mali
logo: mali.gif
institution: MaliMétéo
zoom: 5
shapes_adm:
    - name: Provinces
      color: black
      sql: select gid as key, caption as label, ST_AsBinary(the_geom) as the_geom
                  from mal_level_1
      is_checked: True
    - name: Districts
      color: grey
      sql: select gid as key, label, ST_AsBinary(the_geom) as the_geom
                from mal_level_2
      is_checked: True

# Onset
onset:

    # Data

    #Daily ENACTS Zarr conversion
    rr_mrg_nc_path: /Data/data23/MaliMeteo/ENACTS/ALL/mrg_precip_daily/
    rr_mrg_resolution: .0375
    rr_mrg_chunks:
        T: 600
        Y: 23
        X: 24
    rr_mrg_zarr_path: /data/remic/mydatafiles/MaliMeteo/ENACTS/ALL/mrg_precip_daily/
          
    # App
    core_path: /onset

    # Onset_and_Cessation
    app_title: Growing Season Maproom
    onset_and_cessation_title: Planting and Harvest Decision Support Maproom
    default_search_month: Jun
    default_running_days: 5
    default_min_rainy_days: 3
    ison_cess_date_hist: True
    map_text:
        monit:
            menu_label: Has germinating rain occured?
            description: The map shows the result of the germinating rain date search
            (i.e. near-real time thus without checking of follow-up dry spells)
            from the most recent Early Start to now
            (or the last day with available rainfall data).
            Dates are expressed in days since an Early Start date.
        mean:
            menu_label: When to prepare for planting?
            description: The map shows the average onset date over all years of available data.
            Dates are expressed in days since an Early Start date.
        stddev:
            menu_label: How uncertain is the planting date?
            description: The map shows the standard deviation from the average onset date.
            over all years of available data.
            Dates are expressed in days since an Early Start date.
        pe:
            menu_label: How risky to plant...
            description: The map shows the probability of the onset date to be past a certain date,
            through all the years of available data.
            Dates are expressed in days since an Early Start date.