# Zambia
zoom: 6
map_center: [-13., 28.]
logo: 200px-coat_of_arms_of_zambia.png
institution: ZMD
shapes_adm:
    - name: National
      color: black
      sql: select 0 as key, 'Zambia' as label,
          ST_AsBinary(ST_Simplify(ST_Union(the_geom), .01)) as the_geom
          from zmprov
      is_checked: True
    - name: Provinces
      color: black
      sql: select gid as key, newfield1 as label, ST_AsBinary(ST_Simplify(the_geom, .01)) as the_geom
          from zmprov
      is_checked: True
    - name: Districts
      color: grey
      sql: select gid as key, district as label, ST_AsBinary(ST_Simplify(the_geom, .01)) as the_geom
          from zambia_districts
      is_checked: True

# Zarr conversion
nc_path: /Data/data23/Zambia/ #top level directory to nc data
zarr_resolution: null #set to null for no regridding
zarr_path: /data/remic/mydatafiles/ZMD/ #top level directory to nc data

data_dir: /data/aaron/zmd/enacts/v3/dekadal
vars:
   #var name in file name:
   #    - input file path relative to nc_path
   #    - output file path relative to zarr_path (set to null if same as input file path)
   #    - var name def in file
    precip: 
        - ALL_20200917/MERGED_precip_daily/
        - null
        - precip
    tmax: 
        - ALL_20200917/MERGED_tmax_daily/
        - null
        - temp
    tmin: 
        - ALL_20200917/MERGED_tmin_daily/
        - null
        - temp

data_src:
    rfe: /Data/data23/Zambia/ALL_20200917/MERGED_precip_dekad/
    tmin: /Data/data23/Zambia/ALL_20200917/MERGED_tmin_dekad/
    tmax: /Data/data23/Zambia/ALL_20200917/MERGED_tmax_dekad/

chunks: #consider changing chunk sizes if regridding
    T: 360
    Y: 27
    X: 25

url_path_prefix: /python_maproom

# Climate Analysis -- Monthly
monthly:

    # App set up
    prefix: /monthly-climatology
    map_title: Monthly Climatology Maproom

    vars:
        Rainfall:
            id: rfe
            min: 0
            max: 500
        Minimum Temperature:
            id: tmin
            min: -5
            max: 40
        Maximum Temperature:
            id: tmax
            min: -5
            max: 40

# Flexible Forecast
flex_fcst:
  
    # App set up
    core_path: /flex-fcst

    # Forecast options
    forecast_path: /data/remic/mydatafiles/ZMD/nextgenzmd
    y_transform: false
    start_regex: '[A-Z][a-z]{2}\d{4}'
    start_format_in: '%b%Y'
    start_format_out: '%b%Y'
    forecast_mu_file_pattern: NextGen_PRCPPRCP_*FCST_mu_SLtarget.tsv
    forecast_var_file_pattern: NextGen_PRCPPRCP_*FCST_var_SLtarget.tsv
    obs_file_pattern: obs_PRCP_SLtarget.tsv 
    hcst_file_pattern: None
    variable: Precipitation

    # S,L, target dates options
    target_period_length: 3
    time_units: months
    leads: null
    targets: ["Oct-Dec", "Nov-Jan", "Dec-Feb"]

# Onset
onset:
  
    # App
    core_path: /onset

    # Onset_and_Cessation
    app_title: Growing Season Maproom
    onset_and_cessation_title: Planting and Harvest Decision Support Maproom
    default_search_month: Nov
    default_running_days: 5
    default_min_rainy_days: 3
    ison_cess_date_hist: True
    map_text:
        monit:
            menu_label: Has germinating rain occured?
            description: The map shows the result of the germinating rain date search
                (i.e. near-real time thus without checking of follow-up dry spells)
                from the most recent Early Start to now
                (or the last day with available rainfall data).
                Dates are expressed in days since an Early Start date.
        mean:
            menu_label: When to prepare for planting?
            description: The map shows the average onset date over all years of available data.
                Dates are expressed in days since an Early Start date.
        stddev:
            menu_label: How uncertain is the planting date?
            description: The map shows the standard deviation from the average onset date.
                over all years of available data.
                Dates are expressed in days since an Early Start date.
        pe:
            menu_label: How risky to plant...
            description: The map shows the probability of the onset date to be past a certain date,
                through all the years of available data.
                Dates are expressed in days since an Early Start date.
        length_mean:
            menu_label: How long is the rainy season?
            description: The map shows the average length (in days) of the rainy season,
                defined as the period between onset and cessation dates,
                over all years of available data.
            map_max: 180
        length_stddev:
            menu_label: How uncertain is the length of the rainy season?
            description: The map shows the standard deviation from the average length of the season,
                over all years of available data.
            map_max: 40
        length_pe:
            menu_label: How likely is the rainy season lasting less than...
            description: The map shows the probability of the rainy season
                to last less than a certain number of days through all the years of available data.
        #total_mean:
        #    menu_label: How much rain falls in the rainy season?
        #    description: The map shows the average precipitation (in mm)  during the rainy season,
        #        defined as the period between onset and cessation dates,
        #        over all years of available data.
        #total_stddev:
        #    menu_label: How uncertain is the amount of rain in the rainy season?
        #    description: The map shows the standard deviation from the average precipitation in the season,
        #        over all years of available data.
        #total_pe:
        #    menu_label: How likely is it raining less than...
        #    description: The map shows the probability of precipitation in the rainy season
        #        being less than a certain amount through all the years of available data.

