# App set up
mode: debug  # debug, devel or prod
server: 127.0.0.1
port: 8050
loglevel: info
dev_processes: 4

db:
    dbname: iridb
    host: dlcomputemon1.iri.columbia.edu
    port: 5432
    user: ingrid  # user name
    password: SNIP
