# Ghana
logo: GMet_Logo.jpg
institution: GhanaMet
zoom: 6
shapes_adm:
    - name: Country
      color: black
      sql: select adm0_code as key, adm0_name as label, ST_AsBinary(the_geom) as the_geom
              from g2015_2012_0 where adm0_code = 94
      is_checked: True
    - name: Regions
      color: black
      sql: select gid as key, adm1_name as label, ST_AsBinary(the_geom) as the_geom
              from g2015_2014_1 where gid between 688 and 697
      is_checked: True 
    - name: Districts
      color: grey
      sql: select gid as key, adm2_name as label, ST_AsBinary(the_geom) as the_geom
              from g2015_2014_2 where gid between 6231 and 6446
      is_checked: True
          
# Daily ENACTS Zarr conversion
daily:
    nc_path: /Data/data23/ #top level directory to nc data
    zarr_resolution: null #set to null for no regridding
    chunks: #if regridding, consider updating sizes
        T: 600
        Y: 15
        X: 29
    zarr_path: /data/remic/mydatafiles/ #top level directory to zarr data
    vars:
       #var name in file name:
       #    - input file path relative to nc_path
       #    - output file path relative to zarr_path (set to null if same as input file path)
       #    - var name def in file
        precip:
            - Ghana/version3/GHANA_ENACTS/ALL/mrg_precip_daily/ 
            - null 
            - precip
        tmax: 
            - Ghana/version3/GHANA_ENACTS/ALL/mrg_tmax_daily/
            - null
            - temp
        tmin: 
            - Ghana/version3/GHANA_ENACTS/ALL/mrg_tmin_daily/
            - null
            - temp

# Dekadal ENACTS Zarr conversion
dekadal:
    nc_path: /Data/data23/ #top level directory to nc data
    zarr_resolution: null #set to null for no regridding
    chunks: #if regridding, consider updating sizes
        T: 360
        Y: 15
        X: 29
    zarr_path: /data/remic/mydatafiles/ #top level directory to zarr data
    vars:
        precip:
            - Ghana/version3/GHANA_ENACTS/ALL/mrg_precip_dekad/
            - null
            - precip
        tmax:
            - Ghana/version3/GHANA_ENACTS/ALL/mrg_tmax_dekad/
            - null
            - temp
        tmin:
            - Ghana/version3/GHANA_ENACTS/ALL/mrg_tmin_dekad/
            - null
            - temp

# Onset
onset:

    # Onset_and_Cessation
    default_search_month: Jun
    default_running_days: 5
    default_min_rainy_days: 3
    ison_cess_date_hist: True
    map_text:
        length_mean:
            map_max: 180
        length_stddev:
            map_max: 40
