# Ethiopia
logo: Ethiopia_IRI_98x48.png
institution: NMA
zoom: 5
shapes_adm:
    - name: National
      color: black
      sql: select 0 as key, 'Ethiopia' as label,
          ST_AsBinary(ST_Simplify(ST_Union(the_geom), .01)) as the_geom
          from eth_regions_dd
      is_checked: True
    - name: Regions
      color: black
      sql: select gid as key, name_1 as label, ST_AsBinary(the_geom) as the_geom
                  from eth_regions_dd
      is_checked: True
    - name: Zones
      color: grey
      sql: select gid as key, (name_2 || ', ' || name_1)  as label, ST_AsBinary(the_geom) as the_geom
                from eth_zones_dd
      is_checked: True
    - name: Woredas
      color: grey
      sql: select gid as key, (name_3 || ', ' || name_2 || ', ' || name_1) as label, ST_AsBinary(the_geom) as the_geom
                  from eth_woredas_dd
      is_checked: False

# Daily ENACTS Zarr conversion
nc_path: /Data/data23/NMA_Ethiopia_v7/ALL_NEW/ #top level directory path to find input data
zarr_resolution: null #set to null for no regridding
chunks: 
    T: 578
    Y: 25
    X: 31
zarr_path: /data/drewr/Ethiopia/NMA_Ethiopia_v7/ALL_NEW/ #top level directory path to put output file
vars: 
   #var name in file name: [input file path, output file path, var name def in file]
    precip: [Rainfall/daily/, Rainfall/daily/rr_mrg_ALL/, precip]
    tmax: [Temperature/daily/tmax/, Temperature/daily/tmax/tmax_mrg_ALL/, temp]
    tmin: [Temperature/daily/tmin/, Temperature/daily/tmin/tmin_mrg_ALL/, temp]

# Onset
onset:

    # App
    core_path: /onset

    # Onset_and_Cessation
    app_title: Growing Season Maproom
    onset_and_cessation_title: Planting and Harvest Decision Support Maproom
    default_search_month: Jun
    default_running_days: 5
    default_min_rainy_days: 3
    ison_cess_date_hist: True
    map_text:
        monit:
            menu_label: Has germinating rain occured?
            description: The map shows the result of the germinating rain date search
                (i.e. near-real time thus without checking of follow-up dry spells)
                from the most recent Early Start to now
                (or the last day with available rainfall data).
                Dates are expressed in days since an Early Start date.
        mean:
            menu_label: When to prepare for planting?
            description: The map shows the average onset date over all years of available data.
                Dates are expressed in days since an Early Start date.
        stddev:
            menu_label: How uncertain is the planting date?
            description: The map shows the standard deviation from the average onset date.
                over all years of available data.
                Dates are expressed in days since an Early Start date.
        pe:
            menu_label: How risky to plant...
            description: The map shows the probability of the onset date to be past a certain date,
                through all the years of available data.
                Dates are expressed in days since an Early Start date.
