# App set up
mode: debug  # debug, devel or prod
server: 127.0.0.1
port: 8050
loglevel: info

db:
    dbname: iridb
    host: dlcomputemon1.iri.columbia.edu
    port: 5432
    user: ingrid  # user name
    password: SNIP

# Senegal
logo: anacimLogo.jpg
institution: ANACIM
zoom: 7
shapes_adm:
        - name: Régions
          color: black
          sql: select id_1 as key, name_1 as label, ST_AsBinary(the_geom) as the_geom
                  from sen_adm1
          is_checked: True
        - name: Départements
          color: grey
          sql: select id_2 as key, name_2 as label, ST_AsBinary(the_geom) as the_geom
                  from sen_adm2
          is_checked: True
        - name: Arrondissements
          color: black
          sql: select id_3 as key, name_3 as label, ST_AsBinary(the_geom) as the_geom
                  from sen_adm3
          is_checked: False
        - name: Commune
          color: grey
          sql: select id_4 as key, name_4 as label, ST_AsBinary(the_geom) as the_geom
                  from sen_adm4
          is_checked: False