# Senegal
logo: anacimLogo.jpg
institution: ANACIM
zoom: 7
shapes_adm:
    - name: Pays
      color: black
      sql: select id_0 as key, name_0 as label, ST_AsBinary(the_geom) as the_geom
              from sen_adm0
      is_checked: False
    - name: Régions
      color: black
      sql: select id_1 as key, name_1 as label, ST_AsBinary(the_geom) as the_geom
          from sen_adm1
      is_checked: True
    - name: Départements
      color: grey
      sql: select id_2 as key, name_2 as label, ST_AsBinary(the_geom) as the_geom
          from sen_adm2
      is_checked: True
    - name: Arrondissements
      color: black
      sql: select id_3 as key, name_3 as label, ST_AsBinary(the_geom) as the_geom
          from sen_adm3
      is_checked: False
    - name: Commune
      color: grey
      sql: select id_4 as key, name_4 as label, ST_AsBinary(the_geom) as the_geom
          from sen_adm4
      is_checked: False

# Onset
onset:

    # Data

    #Daily ENACTS Zarr conversion
    rr_mrg_nc_path: /Data/data23/ANACIM/anacim_v3/ALL_block2/rr_mrg_daily/
    rr_mrg_resolution: .0375
    rr_mrg_chunks:
        T: 592
        Y: 31
        X: 29
    rr_mrg_zarr_path: /data/aaron/ANACIM/anacim_v3/ALL_block2/rr_mrg_daily
      
    # App
    core_path: /onset

    # Onset_and_Cessation
    app_title: Growing Season Maproom
    onset_and_cessation_title: Planting and Harvest Decision Support Maproom
    default_search_month: May
    default_running_days: 3
    default_min_rainy_days: 1
    ison_cess_date_hist: False
    map_text:
        monit:
            menu_label: Has germinating rain occured?
            description: The map shows the result of the germinating rain date search
                (i.e. near-real time thus without checking of follow-up dry spells)
                from the most recent Early Start to now
                (or the last day with available rainfall data).
                Dates are expressed in days since an Early Start date.
        mean:
            menu_label: When to prepare for planting?
            description: The map shows the average onset date over all years of available data.
                Dates are expressed in days since an Early Start date.
        stddev:
            menu_label: How uncertain is the planting date?
            description: The map shows the standard deviation from the average onset date.
                over all years of available data.
                Dates are expressed in days since an Early Start date.
        pe:
            menu_label: How risky to plant...
            description: The map shows the probability of the onset date to be past a certain date,
                through all the years of available data.
                Dates are expressed in days since an Early Start date.
