logo: anacimLogo.jpg
institution: ANACIM
zoom: 7

datasets:
    shapes_adm:
        - name: Pays
          color: black
          sql: select id_0 as key, name_0 as label, ST_AsBinary(the_geom) as the_geom
                  from sen_adm0
          is_checked: False
        - name: Regions
          color: black
          sql: select id_1 as key, name_1 as label, ST_AsBinary(the_geom) as the_geom
              from sen_adm1
          is_checked: True

    # Daily ENACTS Zarr conversion
    daily:
        nc_path: /Data/data23/
        zarr_resolution: null #set to null for no regridding
        chunks: #consider changing chunk sizes if regridding
            T: 592
            Y: 31
            X: 29
        zarr_path: /data/remic/mydatafiles/
        vars:
           #var name in file name:
           #    - input file path relative to nc_path
           #    - output file path relative to zarr_path (set to null if same as input file path)
           #    - var name def in file
            precip: 
                - ANACIM/anacim_v3/ALL_block2/rr_mrg_daily/
                - null
                - precip
            tmax: 
                - ANACIM/anacim_v3/ALL_block2/tx_mrg_daily/
                - null
                - temp
            tmin: 
                - ANACIM/anacim_v3/ALL_block2/tn_mrg_daily/
                - null
                - temp
            et0:
                - ANACIM/anacim_v4/ET0/
                - ANACIM/anacim_v4/ET0/zarr/
                - et0

    # Dekadal ENACTS Zarr conversion
    dekadal:
        nc_path: /Data/data23/
        zarr_resolution: null #set to null for no regridding
        chunks: #consider changing chunk sizes if regridding
            T: 360
            Y: 31
            X: 29
        zarr_path: /data/remic/mydatafiles/
        vars:
           #var name in file name:
           #    - input file path relative to nc_path
           #    - output file path relative to zarr_path (set to null if same as input file path)
           #    - var name def in file
            precip: 
                - ANACIM/anacim_v3/ALL_block2/rr_mrg_dekad/
                - null
                - precip
            tmax: 
                - ANACIM/anacim_v3/ALL_block2/tx_mrg_dekad/
                - null
                - temp
            tmin: 
                - ANACIM/anacim_v3/ALL_block2/tn_mrg_dekad/
                - null
                - temp

maprooms:
    # Onset
    onset:
    - core_path: onset
      title: Growing Season Maproom
      onset_and_cessation_title: Planting and Harvest Decision Support Maproom
      default_search_month: May
      default_search_month_cess: Sep
      default_running_days: 3
      default_min_rainy_days: 1
      ison_cess_date_hist: True
      map_text:
          length_mean:
              map_max: 180
          length_stddev:
              map_max: 40

    wat_bal: null
    crop_suitability: null
    
    monthly:
    - core_path: monthly-climatology
      title: Monthly Climatology Maproom
      vars:
        Rainfall:
          max: 350
        Minimum Temperature:
          min: -5
          max: 40
        Maximum Temperature:
          min: -5
          max: 40
    
    flex_fcst: null
