# App set up
mode: debug  # debug, devel or prod
server: 127.0.0.1
port: 8050
loglevel: info

db:
    dbname: iridb
    host: dlcomputemon1.iri.columbia.edu
    port: 5432
    user: ingrid  # user name
    password: SNIP
    
# Mali
logo: mali.gif
institution: MaliMétéo
zoom: 5
shapes_adm:
        - name: Provinces
          color: black
          sql: select gid as key, caption as label, ST_AsBinary(the_geom) as the_geom
                  from mal_level_1
          is_checked: True
        - name: Districts
          color: grey
          sql: select gid as key, label, ST_AsBinary(the_geom) as the_geom
                  from mal_level_2
          is_checked: True