# App set up
mode: debug  # debug, devel or prod
server: 127.0.0.1
port: 8050
loglevel: info

db:
    dbname: iridb
    host: dlcomputemon1.iri.columbia.edu
    port: 5432
    user: ingrid  # user name
    password: SNIP
    
#Guatemala
zoom: 7
shapes_adm:
    - name: Country
      color: black
      sql: select adm0_code as key, adm0_name as label, ST_AsBinary(coarse_geom) as the_geom
          from g2015_2012_0
      is_checked: True