logo: anacimLogo.jpg
institution: ANACIM
zoom: 7

datasets:
    shapes_adm:
        - name: Pays
          color: black
          sql: select id_0 as key, name_0 as label, ST_AsBinary(the_geom) as the_geom
                  from sen_adm0
          is_checked: False
        - name: Regions
          color: black
          sql: select id_1 as key, name_1 as label, ST_AsBinary(the_geom) as the_geom
              from sen_adm1
          is_checked: True

    # Daily ENACTS Zarr conversion
    daily:
        nc_path: /Data/data23/
        zarr_resolution: null #set to null for no regridding
        chunks: #consider changing chunk sizes if regridding
            T: 592
            Y: 31
            X: 29
        zarr_path: /data/remic/mydatafiles/
        vars:
           #var name in file name:
           #    - input file path relative to nc_path
           #    - output file path relative to zarr_path (set to null if same as input file path)
           #    - var name def in file
            precip: 
                - ANACIM/anacim_v3/ALL_block2/rr_mrg_daily/
                - null
                - precip
            tmax: 
                - ANACIM/anacim_v3/ALL_block2/tx_mrg_daily/
                - null
                - temp
            tmin: 
                - ANACIM/anacim_v3/ALL_block2/tn_mrg_daily/
                - null
                - temp
            et0:
                - ANACIM/anacim_v4/ET0/
                - ANACIM/anacim_v4/ET0/zarr/
                - et0

    # Dekadal ENACTS Zarr conversion
    #dekadal: # Same-same as daily

maprooms:
    # Onset
    onset:

        # Onset_and_Cessation
        default_search_month: May
        default_search_month_cess: Sep
        default_running_days: 3
        default_min_rainy_days: 1
        ison_cess_date_hist: True
        map_text:
            length_mean:
                map_max: 180
            length_stddev:
                map_max: 40

    # Water Balance Monitoring
    wat_bal:

        planting_month: Jun
        crop_name: Rice
        kc_v: [0, 0, 1.1, 1.1, 0]
        kc_l: [3, 27, 45, 60]
        taw_file: /data/remic/mydatafiles/soilgrids/Senegal/GYGA_ERZD_wat_cap_abs_anacim_enacts3.nc
        taw_max: 136

    crop_suitability:
        - title: CSC
          core_path: crops_climate_suitability
          app_title: Climate Suitability for Crops
          crop_suit_title: Climate Suitability for Crops
          map_text:
              suitability:
                  menu_label: Crop climate suitability
                  description: The map shows the count of suitable climate conditions for a specific crop.
                  units: integer index
              precip:
                  menu_label: Precipitation
                  description: Seasonal Precipitation Total.
                  units: mm
                  map_max: 400
                  map_min: 0
              tmax:
                  menu_label: Maximum temperature
                  description: Seasonal Maximum Temperature.
                  units: C
                  map_max: 42
                  map_min: 10
              tmin:
                  menu_label: Minimum temperature
                  description: Seasonal Minimum Temperature.
                  units: C
                  map_max: 32
                  map_min: 0
          param_defaults:
              target_season: 2 # DFJ, MAM, JJA, SON 
              lower_wet_thresh: 500 #mm; cumulative for the season
              upper_wet_thresh: 700 #mm; cumulative for the season
              min_temp: 10 #C
              max_temp: 25 #C
              temp_range: 15 #C; amplitude: `max_temp - min_temp`
              season_length: 75 #days 
              min_wet_days: 60 #days
              wet_day_def: 1 #mm

    monthly: null
    flex_fcst: null
