[project]
authors = ["Aaron Kaplan <aaron@iri.columbia.edu>"]
channels = ["conda-forge", "iri-nextgen"]
name = "enactsmaproom"
platforms = ["linux-64", "osx-64", "osx-arm64"]

[tasks]

[system-requirements]
libc = {family="glibc", version="2.17"}

[dependencies]
python = "3.9.*"
bottleneck = "*"
cptio = "*"
dash = "*"
dash-leaflet = "*"
dash-bootstrap-components = "*"
dask = "*"
netcdf4 = "*"
numpy = "*"
opencv = "*"
pandas = "1.3.*"
pip = "*"
psycopg2 = "*"
rasterio = "*"
scipy = "*"
shapely = "*"
werkzeug = "<2.1"
xarray = "*"
yaml = "*"
zarr = "*"

[feature.dev.dependencies]
myst-parser = "*"
pytest = "*"
sphinx = "*"

[environments]
default = {features = ["dev"], solve-group = "prod"}
prod = {features = [], solve-group = "prod"}
