url_path_prefix: /python_maproom

# DB configuration for the production docker environment. Override in
# development environment.
db:
    host: postgres
    port: 5432
    user: ingrid
    dbname: iridb

maprooms:

    projections:

        # App set up
        core_path: projections
        title: Projections
