zoom: 2
url_path_prefix: /python_maproom

# DB configuration for the production docker environment. Override in
# development environment.
db:
    host: postgres
    port: 5432
    user: ingrid
    dbname: iridb

datasets:
    
    shapes_adm:
        - name: National
          color: black
          sql: select adm0_code as key, adm0_name as label,
            ST_AsBinary(ST_SimplifyPreserveTopology(coarse_geom, 0.0025)) as the_geom
            from g2015_2012_0
          is_checked: True
        #- name: Adm2
        #  color: black
        #  sql: select (adm0_code, adm1_code) as key, adm1_name as label,
        #    ST_AsBinary(ST_SimplifyPreserveTopology(the_geom, 0.0025)) as the_geom
        #    from g2015_2014_1
        #  is_checked: False
        #- name: Adm3
        #  color: grey
        #  sql: select (adm0_code, adm1_code, adm2_code) as key, adm2_name as label,
        #    ST_AsBinary(ST_SimplifyPreserveTopology(the_geom, 0.0025)) as the_geom
        #    from g2015_2014_2
        #  is_checked: False

maprooms:

    projections:

        # App set up
        - title: Projections
          core_path: projections
