[project]
name = "pingrid"
channels = []
preview = ["pixi-build"]

[package]
name = "pingrid"
version = "1"

[package.build.backend]
name = "pixi-build-python"
version = "0.4.*"
channels = [
  "https://prefix.dev/pixi-build-backends",
  "conda-forge",
]

[package.host-dependencies]
setuptools = "80.9.*"
