# App

# Zarr conversion
rr_mrg_nc_path: /Data/data23/MaliMeteo/ENACTS/ALL/mrg_precip_daily/
rr_mrg_resolution: .0375
rr_mrg_chunks:
    T: 600
    Y: 23
    X: 24
rr_mrg_zarr_path: /data/remic/mydatafiles/MaliMeteo/ENACTS/ALL/mrg_precip_daily/

# Mali
logo: mali.gif
institution: MaliMétéo
zoom: 5
shapes_adm:
        - name: Provinces
          color: black
          sql: select gid as key, caption as label, ST_AsBinary(the_geom) as the_geom
                  from mal_level_1
          is_checked: True
        - name: Districts
          color: grey
          sql: select gid as key, label, ST_AsBinary(the_geom) as the_geom
                  from mal_level_2
          is_checked: True

# Climate and Ag

# Onset_and_Cessation
default_search_month: Jun
default_running_days: 5
default_min_rainy_days: 3
ison_cess_date_hist: True
