# App

# Zarr conversion
rr_mrg_nc_path: /Data/data23/Ghana/version3/GHANA_ENACTS/ALL/mrg_precip_daily/
rr_mrg_resolution: .0375
rr_mrg_chunks:
    T: 600
    Y: 15
    X: 29
rr_mrg_zarr_path: /data/remic/mydatafiles/Ghana/version3/GHANA_ENACTS/ALL/mrg_precip_daily/

# Ghana
logo: GMet_Logo.jpg
institution: GhanaMet
zoom: 6
shapes_adm:
        - name: Regions
          color: black
          sql: select gid as key, adm1_name as label, ST_AsBinary(the_geom) as the_geom
                  from g2015_2014_1 where gid between 688 and 697
          is_checked: True 
        - name: Districts
          color: grey
          sql: select gid as key, adm2_name as label, ST_AsBinary(the_geom) as the_geom
                  from g2015_2014_2 where gid between 6231 and 6446
          is_checked: True

# Climate and Ag

# Onset_and_Cessation
default_search_month: Jun
default_running_days: 5
default_min_rainy_days: 3
ison_cess_date_hist: True
