# App

# Zarr conversion
rr_mrg_nc_path: /Data/data23/ANACIM/anacim_v3/ALL_block2/rr_mrg_daily/
rr_mrg_resolution: .0375
rr_mrg_chunks:
    T: 592
    Y: 31
    X: 29
rr_mrg_zarr_path: /data/aaron/ANACIM/anacim_v3/ALL_block2/rr_mrg_daily

# Senegal
logo: anacimLogo.jpg
institution: ANACIM
zoom: 7
shapes_adm:
        - name: Régions
          color: black
          sql: select id_1 as key, name_1 as label, ST_AsBinary(the_geom) as the_geom
                  from sen_adm1
          is_checked: True
        - name: Départements
          color: grey
          sql: select id_2 as key, name_2 as label, ST_AsBinary(the_geom) as the_geom
                  from sen_adm2
          is_checked: True
        - name: Arrondissements
          color: black
          sql: select id_3 as key, name_3 as label, ST_AsBinary(the_geom) as the_geom
                  from sen_adm3
          is_checked: False
        - name: Commune
          color: grey
          sql: select id_4 as key, name_4 as label, ST_AsBinary(the_geom) as the_geom
                  from sen_adm4
          is_checked: False

# Climate and Ag

# Onset_and_Cessation
default_search_month: May
default_running_days: 3
default_min_rainy_days: 1
ison_cess_date_hist: False
