# App

# Zarr conversion
rr_mrg_nc_path: /Data/data23/NMA_Ethiopia_v7/ALL_NEW/Rainfall/daily/
rr_mrg_resolution: .25
rr_mrg_chunks:
    T: 578
    Y: 25
    X: 31
rr_mrg_zarr_path: /data/aaron/Ethiopia/NMA_Ethiopia_v7/ALL_NEW/Rainfall/daily/rr_mrg_ALL-staging/


# Ethiopia
logo: Ethiopia_IRI_98x48.png
institution: NMA
zoom: 5
shapes_adm:
        - name: Regions
          color: black
          sql: select gid as key, name_1 as label, ST_AsBinary(the_geom) as the_geom
                  from eth_regions_dd
          is_checked: True
        - name: Zones
          color: grey
          sql: select gid as key, (name_2 || ', ' || name_1)  as label, ST_AsBinary(the_geom) as the_geom
                  from eth_zones_dd
          is_checked: True
        - name: Woredas
          color: grey
          sql: select gid as key, (name_3 || ', ' || name_2 || ', ' || name_1) as label, ST_AsBinary(the_geom) as the_geom
                  from eth_woredas_dd
          is_checked: False

# Climate and Ag

# Onset_and_Cessation
default_search_month: Jun
default_running_days: 5
default_min_rainy_days: 3
ison_cess_date_hist: True
