on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: fbf-test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v0.41.4
          cache: true
          manifest-path: fbfmaproom/pixi.toml

      - run: cd fbfmaproom && pixi run python -m pytest tests/test_pingrid.py
